// ─────────────────────────────────────────────
// PROJECT DATA, extensible, add as many as you want.
// Each project has a slug for routing.
// ─────────────────────────────────────────────

const PROJECTS = [
  {
    slug: 'cryptostream-ai',
    num: '01',
    title: 'CryptoStream',
    titleIt: 'AI',
    year: '2024',
    role: 'Solo build',
    category: 'Data · Streaming',
    summary: 'Real-time crypto pipeline ingesting Coinbase feeds at scale.',
    desc: 'Real-time data pipeline ingesting live Coinbase prices for 11 cryptocurrencies (BTC, ETH, ADA, and more). Python producers publish to Kafka topics, Spark transforms the streams into structured records stored in Cassandra for low-latency querying, and processed data exports to CSV for offline analysis. Forecasts come from ARIMA, VAR, moving-average, and pre-trained LSTM models, surfaced through a Streamlit dashboard with per-coin model selection alongside Grafana for live monitoring. Every component is Dockerized.',
    stack: ['Kafka', 'Spark', 'Cassandra', 'Streamlit', 'Grafana', 'Docker', 'Python'],
    links: { github: 'https://github.com/isiddharthsingh/CryptoStream-AI' },
    highlights: [
      'Engineered a real-time data pipeline using Apache Kafka, Spark, and Cassandra to process, transform, and store high-velocity streaming data from the Coinbase API, enabling low-latency querying.',
      'Implemented forecasting with ARIMA, VAR, moving-average, and LSTM models, keeping pre-trained LSTM models and scalers versioned alongside the pipeline.',
      'Built two visualization layers: Grafana dashboards monitoring Cassandra data in real time, and a Streamlit app for picking coins and models and exploring predictions.',
      'Containerized the stack with Docker and added a Cassandra-to-CSV export path for offline analysis.',
    ],
    accent: 'terminal',
  },
  {
    slug: 'taleweaver',
    num: '02',
    title: 'Tale',
    titleIt: 'weaver',
    year: '2024',
    role: 'Solo build',
    category: 'AI · Multimodal',
    summary: 'Image-to-story generation on a serverless AWS backend.',
    desc: 'Multimodal web app that turns an uploaded photo into a generated short story. AWS Rekognition detects labels in the image, OpenAI writes the narrative from them, and every story ships with a built-in summarization feature. Full user authentication keeps stories private, and each user gets a personal archive of everything they have generated — DynamoDB for storage, Lambda for backend functions, hosted on EC2 behind API Gateway.',
    stack: ['AWS Rekognition', 'OpenAI', 'EC2', 'Lambda', 'DynamoDB', 'Cognito', 'API Gateway'],
    links: { github: 'https://github.com/isiddharthsingh/Taleweaver' },
    highlights: [
      'Built the image-to-story flow on AWS Rekognition label detection feeding OpenAI story generation, with per-story summarization for a quick read.',
      'Implemented full user authentication with a private, per-user story archive stored securely in DynamoDB.',
      'Hosted on AWS EC2 with serverless Lambda functions behind API Gateway and Cognito-managed auth for a secure, low-latency RESTful API.',
    ],
    accent: 'story',
  },
  {
    slug: 'dining-concierge',
    num: '03',
    title: 'Dining',
    titleIt: 'Concierge',
    year: '2023',
    role: 'Solo build',
    category: 'AI · Conversational',
    summary: 'Serverless NLP chatbot for restaurant recommendations.',
    desc: 'NLP-driven serverless chatbot for restaurant recs. Lex + Lambda + API Gateway on the front, with SQS, ElasticSearch, DynamoDB, and SES orchestrated by CloudWatch on the back.',
    stack: ['AWS Lex', 'Lambda', 'API Gateway', 'DynamoDB', 'ElasticSearch', 'SES', 'SQS'],
    links: { github: 'https://github.com/isiddharthsingh/Serverless-Dining-Concierge-Chatbot' },
    highlights: [
      'Designed and deployed a serverless, microservices-based Dining Concierge chatbot using AWS Lex, Lambda, API Gateway, and S3, leveraging NLP for personalized restaurant recommendations.',
      'Automated restaurant suggestion workflows by 50% via SQS, ElasticSearch, DynamoDB, and SES, orchestrated with CloudWatch events.',
    ],
    accent: 'dining',
  },
  {
    slug: 'futeursecure',
    num: '04',
    title: 'Futeur',
    titleIt: 'Secure',
    year: '2025',
    role: 'Futeur AI',
    category: 'Security · Platform',
    summary: 'Post-quantum security and compliance platform for enterprises.',
    desc: 'Enterprise security and compliance platform built at Futeur AI. Post-quantum cryptography (CRYSTALS-Kyber, Dilithium) protects data in transit and at rest, layered detection runs on OSSEC, Wazuh, and Suricata, and Hyperledger Fabric keeps audit trails tamper-proof — NIST-compliant end to end.',
    stack: ['CRYSTALS-Kyber', 'Dilithium', 'OSSEC', 'Wazuh', 'Suricata', 'Hyperledger Fabric'],
    links: { demo: 'https://www.futeursecure.com/' },
    highlights: [
      'Integrated post-quantum cryptography (CRYSTALS-Kyber and Dilithium) to secure data in transit and at rest with 100% NIST compliance and plug-and-play database integration.',
      'Layered OSSEC HIDS, Wazuh, and Suricata IDS/IPS to cut false positives by 60% and improve threat-detection accuracy by 45%.',
      'Built a distributed, tamper-proof logging system on Hyperledger Fabric with analytics dashboards for immutable audit trails.',
    ],
    accent: 'shield',
  },
  {
    slug: 'futeur-vault',
    num: '05',
    title: 'Futeur',
    titleIt: 'Vault',
    year: '2025',
    role: 'Futeur AI',
    category: 'Security · Product',
    summary: 'Team password manager with sharing, revocation, and alerts.',
    desc: 'Web-based password manager for individuals and teams. Credentials are organized by category with associated URLs, one-click copy, visibility toggles, and last-updated tracking. Sharing is built for teams: send a credential to a colleague by email with a personal message, see exactly who has access to what, and revoke it in one click — recipients get email notifications via EmailJS. React and TypeScript on Supabase, with protected routes throughout and dark/light themes.',
    stack: ['React', 'TypeScript', 'Supabase', 'Tailwind', 'shadcn/ui', 'EmailJS'],
    links: { github: 'https://github.com/isiddharthsingh/futeur-wallet', demo: 'https://www.futeursecure.com/vault' },
    highlights: [
      'Built the vault UI in React and TypeScript with category organization, URL association, one-click copy, visibility toggles, and last-updated tracking on every credential.',
      'Shipped team sharing with per-share personal messages, a sharing overview of who has access to which credentials, one-click revocation, and EmailJS notifications to recipients.',
      'Secured the app with protected routes and multi-layered authentication safeguards, and polished the UX with dark/light modes, animated transitions, and toast feedback.',
    ],
    accent: 'vault',
  },
  {
    slug: 'isac-usa',
    num: '06',
    title: 'ISAC',
    titleIt: 'USA',
    year: '2025',
    role: 'Client build',
    category: 'Web · Platform',
    summary: 'Community platform serving thousands of international students.',
    desc: 'Central hub for international students in the US — verified WhatsApp group directories, webinar scheduling, volunteer onboarding, and success stories. Mobile-first and accessible, with an architecture built to hold thousands of concurrent visitors without downtime.',
    stack: ['Responsive UI', 'Accessibility', 'Real-time updates', 'Secure forms'],
    links: { demo: 'https://www.isac-usa.org/' },
    highlights: [
      'Designed and built the ISAC website as a central hub supporting thousands of concurrent visitors with fast load times.',
      'Implemented a mobile-first, accessible UI spanning verified WhatsApp group directories, webinar scheduling, and volunteer onboarding.',
      'Optimized backend workflows for real-time group updates and secure form submissions.',
    ],
    accent: 'globe',
  },
  {
    slug: 'ai-market-analysis',
    num: '07',
    title: 'AI Market',
    titleIt: 'Analysis',
    year: '2025',
    role: 'Solo build',
    category: 'Data · Pipelines',
    summary: 'Airflow pipeline correlating AI and crypto trends across sources.',
    desc: 'Containerized data-engineering pipeline that pulls Reddit, GitHub, and CoinGecko daily to track trends across AI, ML, and crypto. Three Airflow DAGs — extraction and ETL, trend correlation with sentiment analysis, and freshness monitoring — run on Celery and Redis with PostgreSQL storage, all under Docker Compose.',
    stack: ['Airflow', 'Celery', 'Redis', 'PostgreSQL', 'Docker', 'Python'],
    links: { github: 'https://github.com/isiddharthsingh/Ai-Market-Analysis' },
    highlights: [
      'Orchestrated three Airflow DAGs covering extraction and ETL, trend correlation with sentiment analysis, and data freshness and quality monitoring.',
      'Consolidated Reddit, GitHub, and CoinGecko feeds into PostgreSQL with Celery and Redis task execution, fully containerized via Docker Compose.',
    ],
    accent: 'dag',
  },
  {
    slug: 'pygpt2',
    num: '08',
    title: 'PyGPT',
    titleIt: '2',
    year: '2024',
    role: 'Solo build',
    category: 'AI · Research',
    summary: 'GPT-2 (124M) reimplemented and trained from scratch in PyTorch.',
    desc: 'Faithful PyTorch reimplementation of GPT-2, trained from scratch on FineWeb-Edu. Covers tokenization, architecture, single-GPU and distributed training loops, zero-shot HellaSwag evaluation, and sampling — a clear, modular codebase for understanding transformer internals.',
    stack: ['PyTorch', 'DDP', 'FineWeb-Edu', 'HellaSwag', 'Python'],
    links: { github: 'https://github.com/isiddharthsingh/PyGPT2' },
    highlights: [
      'Trained the 124M-parameter model on FineWeb-Edu with both single-GPU and distributed (DDP) setups.',
      'Evaluated zero-shot performance on HellaSwag and built clean generation scripts for text sampling.',
    ],
    accent: 'loss',
  },
  {
    slug: 'gpt-transformer',
    num: '09',
    title: 'GPT',
    titleIt: 'Transformer',
    year: '2024',
    role: 'Solo build',
    category: 'AI · Research',
    summary: 'Character-level transformer language model built from scratch.',
    desc: 'Character-level language model implemented from first principles after "Attention Is All You Need". Multi-head self-attention, positional encoding, and autoregressive generation, written in PyTorch and optimized for GPU acceleration.',
    stack: ['PyTorch', 'Self-attention', 'CUDA', 'Python'],
    links: { github: 'https://github.com/isiddharthsingh/GPT_Transformer' },
    highlights: [
      'Implemented multi-head attention, positional encoding, and the full transformer block stack from scratch.',
      'Generates coherent text by capturing short- and long-range dependencies at the character level.',
    ],
    accent: 'attention',
  },
  {
    slug: 'harmony-ai',
    num: '10',
    title: 'Harmony',
    titleIt: 'AI',
    year: '2024',
    role: 'Team build',
    category: 'AI · Agents',
    summary: 'Slack-native assistant unifying Trello, Gmail, and Calendar.',
    desc: 'AI productivity assistant that lives in Slack. Creates and updates Trello tasks and checklists by command, syncs due dates to Google Calendar, and surfaces unread Gmail directly in channels — one interface, four tools, no context switching.',
    stack: ['Slack API', 'Trello API', 'Gmail API', 'Google Calendar API', 'Python'],
    links: { github: 'https://github.com/isiddharthsingh/mAIgic-nyu/tree/hw3_submission' },
    highlights: [
      'Command-based Trello task and checklist management from inside Slack, with due dates auto-synced to Google Calendar.',
      'Fetches unread Gmail and posts it to Slack channels so important messages surface in real time.',
    ],
    accent: 'hub',
  },
  {
    slug: 'hashtable-benchmark',
    num: '11',
    title: 'Hashtable',
    titleIt: 'Benchmark',
    year: '2024',
    role: 'Solo build',
    category: 'Systems · Concurrency',
    summary: 'Measuring lock strategies on a multithreaded hash table.',
    desc: 'A study of synchronization under contention. A lock-free baseline demonstrates lost updates from race conditions; per-bucket mutexes, reader–writer locks, and spinlocks each fix it at different costs. A driver sweeps thread counts and records insert and retrieve timings for comparison.',
    stack: ['C', 'POSIX threads', 'Mutexes', 'RW locks', 'Spinlocks'],
    links: { github: 'https://github.com/isiddharthsingh/Multithread-Hashtable-Benchmark' },
    highlights: [
      'Demonstrated race-condition data loss with an unlocked baseline, then eliminated it with per-bucket mutexes.',
      'Compared mutex, reader–writer, and spinlock strategies across thread counts, measuring speed, CPU usage, and data integrity.',
    ],
    accent: 'buckets',
  },
  {
    slug: 'resume-maestro',
    num: '12',
    title: 'Resume',
    titleIt: 'Maestro',
    year: '2024',
    role: 'Solo build',
    category: 'AI · Tools',
    summary: 'GPT-4 resume optimizer with LaTeX-quality PDF output.',
    desc: 'Upload a resume, paste a job description, download a tailored PDF. GPT-4 rewrites content against the posting, PyMuPDF handles text extraction, and robust LaTeX templates keep the output typographically sharp. Streamlit front, FastAPI back, Docker throughout.',
    stack: ['GPT-4', 'FastAPI', 'Streamlit', 'LaTeX', 'PyMuPDF', 'Docker'],
    links: { github: 'https://github.com/isiddharthsingh/Resume-Maestro' },
    highlights: [
      'Engineered a Streamlit and FastAPI pipeline that optimizes resume content against job descriptions using GPT-4.',
      'Produced LaTeX and PDF outputs with robust templates and real-time downloads, containerized with Docker.',
    ],
    accent: 'resume',
  },
  {
    slug: 'tubegenie',
    num: '13',
    title: 'Tube',
    titleIt: 'Genie',
    year: '2024',
    role: 'Solo build',
    category: 'AI · RAG',
    summary: 'Ask questions of any YouTube video, answered by GPT-4-turbo.',
    desc: 'Retrieval-augmented Q&A over YouTube content. Embedchain ingests the video, ChromaDB stores the vectors, and GPT-4-turbo answers through an interactive Streamlit UI — with cleanup routines keeping temporary storage lean.',
    stack: ['GPT-4-turbo', 'Embedchain', 'ChromaDB', 'Streamlit', 'Python'],
    links: { github: 'https://github.com/isiddharthsingh/TubeGenie' },
    highlights: [
      'Built ingestion with Embedchain and vector retrieval over ChromaDB for fast, grounded answers about video content.',
      'Interactive Streamlit interface with an efficient cleanup mechanism for temporary data storage.',
    ],
    accent: 'video',
  },
  {
    slug: 'llamalingo',
    num: '14',
    title: 'Llama',
    titleIt: 'Lingo',
    year: '2024',
    role: 'Solo build',
    category: 'AI · Conversational',
    summary: 'Llama-3 chatbot served entirely from a local machine.',
    desc: 'Chatbot on Llama-3, served through LM Studio as an OpenAI-compatible API on a local server — no cloud dependency. Streamlit front end with dynamic chat-history management.',
    stack: ['Llama-3', 'LM Studio', 'Streamlit', 'OpenAI API', 'Python'],
    links: { github: 'https://github.com/isiddharthsingh/LlamaLingo' },
    highlights: [
      'Served Llama-3 locally through LM Studio as an OpenAI-compatible API for private, scalable inference.',
      'Dynamic chat-history management behind a clean Streamlit interface.',
    ],
    accent: 'localchat',
  },
  {
    slug: 'ecostock',
    num: '15',
    title: 'Eco',
    titleIt: 'Stock',
    year: '2024',
    role: 'Solo build',
    category: 'Data · Forecasting',
    summary: 'Stock forecasting driven by ESG metrics and sentiment.',
    desc: 'Stock-price forecasting with ESG signals folded in. ARIMA, SMA, SARIMAX, VARMAX, and OLS models over Alpha Vantage data, enriched with news and social-media sentiment — VARMAX quantified the ESG impact at an optimal AIC of 1338.44.',
    stack: ['Python', 'VARMAX', 'SARIMAX', 'ARIMA', 'Alpha Vantage'],
    links: { github: 'https://github.com/isiddharthsingh/EcoStock-ESG-Driven-Market-Predictions' },
    highlights: [
      'Applied VARMAX to quantify the impact of ESG factors on stock prices, achieving an optimal AIC score of 1338.44.',
      'Ran correlation analysis and time-series EDA linking sentiment scores to stock-market behavior.',
    ],
    accent: 'esg',
  },
  {
    slug: 'typeninja',
    num: '16',
    title: 'Type',
    titleIt: 'Ninja',
    year: '2024',
    role: 'Solo build',
    category: 'Web · Game',
    summary: 'A typing game that takes away your backspace.',
    desc: 'Typing game with live WPM, accuracy, and timing across 20 randomized sentences. Backspace is disabled by design — accuracy is the game. Clean, responsive, playable on anything.',
    stack: ['React', 'JavaScript', 'HTML', 'CSS'],
    links: { github: 'https://github.com/isiddharthsingh/TypeNinja' },
    highlights: [
      'Real-time tracking of typing time, accuracy, and words per minute.',
      'Disabled backspace to force focused, accurate typing across randomized sentences.',
    ],
    accent: 'keys',
  },
  {
    slug: 'shems',
    num: '17',
    title: 'Smart Home',
    titleIt: 'Energy',
    year: '2023',
    role: 'Solo build',
    category: 'Web · Full Stack',
    summary: 'Smart-home dashboard for devices and energy analytics.',
    desc: 'Smart Home Energy Management System — register devices, control them, and watch consumption analytics on dynamic charts. Node.js with hardened auth: pooled connections, hashed passwords, and protection against SQL injection and XSS in a multi-user environment.',
    stack: ['Node.js', 'Bootstrap', 'SQL', 'JavaScript'],
    links: { github: 'https://github.com/isiddharthsingh/Smart-Home-Energy-Management-System-SHEMS' },
    highlights: [
      'Full device lifecycle — add, list, remove — with energy-consumption analysis and graphical dashboards.',
      'Hardened security: pooled connections, hashed passwords, and SQL-injection and XSS protections for concurrent multi-user access.',
    ],
    accent: 'energy',
  },
];

Object.assign(window, { PROJECTS });
