// ─────────────────────────────────────────────
// PROJECT DATA, extensible, add as many as you want.
// Each project has a slug for routing.
// ─────────────────────────────────────────────

const PROJECTS = [
  {
    slug: 'cryptostream-ai',
    num: '01',
    title: 'CryptoStream',
    titleIt: 'AI',
    year: '2024',
    role: 'Solo build',
    category: 'Data · Streaming',
    summary: 'Real-time crypto pipeline ingesting Coinbase feeds at scale.',
    desc: 'Real-time data pipeline ingesting live Coinbase prices for 11 cryptocurrencies (BTC, ETH, ADA, and more). Python producers publish to Kafka topics, Spark transforms the streams into structured records stored in Cassandra for low-latency querying, and processed data exports to CSV for offline analysis. Forecasts come from ARIMA, VAR, moving-average, and pre-trained LSTM models, surfaced through a Streamlit dashboard with per-coin model selection alongside Grafana for live monitoring. Every component is Dockerized.',
    stack: ['Kafka', 'Spark', 'Cassandra', 'Streamlit', 'Grafana', 'Docker', 'Python'],
    links: { github: 'https://github.com/isiddharthsingh/CryptoStream-AI' },
    highlights: [
      'Engineered a real-time data pipeline using Apache Kafka, Spark, and Cassandra to process, transform, and store high-velocity streaming data from the Coinbase API, enabling low-latency querying.',
      'Implemented forecasting with ARIMA, VAR, moving-average, and LSTM models, keeping pre-trained LSTM models and scalers versioned alongside the pipeline.',
      'Built two visualization layers: Grafana dashboards monitoring Cassandra data in real time, and a Streamlit app for picking coins and models and exploring predictions.',
      'Containerized the stack with Docker and added a Cassandra-to-CSV export path for offline analysis.',
    ],
    accent: 'terminal',
  },
  {
    slug: 'taleweaver',
    num: '02',
    title: 'Tale',
    titleIt: 'weaver',
    year: '2024',
    role: 'Solo build',
    category: 'AI · Multimodal',
    summary: 'Image-to-story generation on a serverless AWS backend.',
    desc: 'Multimodal web app that turns an uploaded photo into a generated short story. AWS Rekognition detects labels in the image, OpenAI writes the narrative from them, and every story ships with a built-in summarization feature. Full user authentication keeps stories private, and each user gets a personal archive of everything they have generated — DynamoDB for storage, Lambda for backend functions, hosted on EC2 behind API Gateway.',
    stack: ['AWS Rekognition', 'OpenAI', 'EC2', 'Lambda', 'DynamoDB', 'Cognito', 'API Gateway'],
    links: { github: 'https://github.com/isiddharthsingh/Taleweaver' },
    highlights: [
      'Built the image-to-story flow on AWS Rekognition label detection feeding OpenAI story generation, with per-story summarization for a quick read.',
      'Implemented full user authentication with a private, per-user story archive stored securely in DynamoDB.',
      'Hosted on AWS EC2 with serverless Lambda functions behind API Gateway and Cognito-managed auth for a secure, low-latency RESTful API.',
    ],
    accent: 'story',
  },
  {
    slug: 'dining-concierge',
    num: '03',
    title: 'Dining',
    titleIt: 'Concierge',
    year: '2023',
    role: 'Solo build',
    category: 'AI · Conversational',
    summary: 'Serverless NLP chatbot for restaurant recommendations.',
    desc: 'NLP-driven serverless chatbot for restaurant recs. Lex + Lambda + API Gateway on the front, with SQS, ElasticSearch, DynamoDB, and SES orchestrated by CloudWatch on the back.',
    stack: ['AWS Lex', 'Lambda', 'API Gateway', 'DynamoDB', 'ElasticSearch', 'SES', 'SQS'],
    links: { github: 'https://github.com/isiddharthsingh/Serverless-Dining-Concierge-Chatbot' },
    highlights: [
      'Designed and deployed a serverless, microservices-based Dining Concierge chatbot using AWS Lex, Lambda, API Gateway, and S3, leveraging NLP for personalized restaurant recommendations.',
      'Automated restaurant suggestion workflows by 50% via SQS, ElasticSearch, DynamoDB, and SES, orchestrated with CloudWatch events.',
    ],
    accent: 'dining',
  },
  {
    slug: 'futeursecure',
    num: '04',
    title: 'Futeur',
    titleIt: 'Secure',
    year: '2025',
    role: 'Futeur AI',
    category: 'Security · Platform',
    summary: 'Post-quantum security and compliance platform for enterprises.',
    desc: 'Enterprise security and compliance platform built at Futeur AI. Post-quantum cryptography (CRYSTALS-Kyber, Dilithium) protects data in transit and at rest, layered detection runs on OSSEC, Wazuh, and Suricata, and Hyperledger Fabric keeps audit trails tamper-proof — NIST-compliant end to end.',
    stack: ['CRYSTALS-Kyber', 'Dilithium', 'OSSEC', 'Wazuh', 'Suricata', 'Hyperledger Fabric'],
    links: { demo: 'https://www.futeursecure.com/' },
    highlights: [
      'Integrated post-quantum cryptography (CRYSTALS-Kyber and Dilithium) to secure data in transit and at rest with 100% NIST compliance and plug-and-play database integration.',
      'Layered OSSEC HIDS, Wazuh, and Suricata IDS/IPS to cut false positives by 60% and improve threat-detection accuracy by 45%.',
      'Built a distributed, tamper-proof logging system on Hyperledger Fabric with analytics dashboards for immutable audit trails.',
    ],
    accent: 'shield',
  },
  {
    slug: 'futeur-vault',
    num: '05',
    title: 'Futeur',
    titleIt: 'Vault',
    year: '2025',
    role: 'Futeur AI',
    category: 'Security · Product',
    summary: 'Team password manager with sharing, revocation, and alerts.',
    desc: 'Web-based password manager for individuals and teams. Credentials are organized by category with associated URLs, one-click copy, visibility toggles, and last-updated tracking. Sharing is built for teams: send a credential to a colleague by email with a personal message, see exactly who has access to what, and revoke it in one click — recipients get email notifications via EmailJS. React and TypeScript on Supabase, with protected routes throughout and dark/light themes.',
    stack: ['React', 'TypeScript', 'Supabase', 'Tailwind', 'shadcn/ui', 'EmailJS'],
    links: { github: 'https://github.com/isiddharthsingh/futeur-wallet', demo: 'https://www.futeursecure.com/vault' },
    highlights: [
      'Built the vault UI in React and TypeScript with category organization, URL association, one-click copy, visibility toggles, and last-updated tracking on every credential.',
      'Shipped team sharing with per-share personal messages, a sharing overview of who has access to which credentials, one-click revocation, and EmailJS notifications to recipients.',
      'Secured the app with protected routes and multi-layered authentication safeguards, and polished the UX with dark/light modes, animated transitions, and toast feedback.',
    ],
    accent: 'vault',
  },
  {
    slug: 'isac-usa',
    num: '06',
    title: 'ISAC',
    titleIt: 'USA',
    year: '2025',
    role: 'Client build',
    category: 'Web · Platform',
    summary: 'Community platform serving thousands of international students.',
    desc: 'Central hub for international students in the US — verified WhatsApp group directories, webinar scheduling, volunteer onboarding, and success stories. Mobile-first and accessible, with an architecture built to hold thousands of concurrent visitors without downtime.',
    stack: ['Responsive UI', 'Accessibility', 'Real-time updates', 'Secure forms'],
    links: { demo: 'https://www.isac-usa.org/' },
    highlights: [
      'Designed and built the ISAC website as a central hub supporting thousands of concurrent visitors with fast load times.',
      'Implemented a mobile-first, accessible UI spanning verified WhatsApp group directories, webinar scheduling, and volunteer onboarding.',
      'Optimized backend workflows for real-time group updates and secure form submissions.',
    ],
    accent: 'globe',
  },
  {
    slug: 'ai-market-analysis',
    num: '07',
    title: 'AI Market',
    titleIt: 'Analysis',
    year: '2025',
    role: 'Solo build',
    category: 'Data · Pipelines',
    summary: 'Airflow pipeline correlating AI and crypto trends across sources.',
    desc: 'Containerized pipeline built around a concrete question: does social-media hype around AI correlate with real developer activity? Airflow DAGs pull roughly 400 Reddit posts across 8 AI/ML subreddits, about 200 trending AI repositories from GitHub, and around 200 crypto projects from CoinGecko every day, then run ETL, sentiment analysis, trend correlation, and data-quality checks — Celery workers over a Redis broker, PostgreSQL as the warehouse, all under Docker Compose.',
    stack: ['Airflow', 'Celery', 'Redis', 'PostgreSQL', 'Docker', 'Python'],
    links: { github: 'https://github.com/isiddharthsingh/Ai-Market-Analysis' },
    highlights: [
      'Orchestrated three Airflow DAGs — extraction and ETL, trend correlation with sentiment analysis, and data freshness and quality monitoring — executed in parallel by Celery workers over Redis.',
      'Consolidated ~400 daily Reddit posts (8 subreddits), ~200 GitHub AI repositories, and ~200 CoinGecko crypto projects into a PostgreSQL warehouse queryable with plain SQL.',
      'Designed for longitudinal analysis: correlation results strengthen over 7–30 day collection windows, with data-quality metrics tracked inside the pipeline itself.',
    ],
    accent: 'dag',
  },
  {
    slug: 'pygpt2',
    num: '08',
    title: 'PyGPT',
    titleIt: '2',
    year: '2024',
    role: 'Solo build',
    category: 'AI · Research',
    summary: 'GPT-2 (124M) reimplemented and trained from scratch in PyTorch.',
    desc: 'GPT-2 rebuilt from scratch in PyTorch — transformer blocks, causal self-attention, and position embeddings, with no reliance on existing GPT-2 implementations. The 124M-parameter model pretrains on 10B tokens of FineWeb-Edu through a custom preprocessing and tokenization pipeline, scales across GPUs with DistributedDataParallel, and is evaluated zero-shot on HellaSwag.',
    stack: ['PyTorch', 'DDP', 'FineWeb-Edu', 'HellaSwag', 'Python'],
    links: { github: 'https://github.com/isiddharthsingh/PyGPT2' },
    highlights: [
      'Implemented the full GPT-2 architecture from the GPT-2 and GPT-3 papers: transformer blocks, causal self-attention, and position embeddings, entirely in PyTorch.',
      'Preprocessed and tokenized FineWeb-Edu into a pretraining pipeline and trained the 124M model on 10B tokens, on both single-GPU and multi-GPU DDP setups via torchrun.',
      'Evaluated zero-shot reasoning on HellaSwag, reaching 29.55% completion-style accuracy with the 124M model, and generates coherent continuations from prompts.',
    ],
    accent: 'loss',
  },
  {
    slug: 'gpt-transformer',
    num: '09',
    title: 'GPT',
    titleIt: 'Transformer',
    year: '2024',
    role: 'Solo build',
    category: 'AI · Research',
    summary: 'Character-level transformer language model built from scratch.',
    desc: 'Character-level language model implemented from first principles after "Attention Is All You Need". Multi-head self-attention with residual connections and layer normalization, sinusoidal positional encodings, and dropout regularization, trained with AdamW and periodic validation — generating Shakespeare-style text autoregressively, on CPU or CUDA.',
    stack: ['PyTorch', 'Self-attention', 'CUDA', 'Python'],
    links: { github: 'https://github.com/isiddharthsingh/GPT_Transformer' },
    highlights: [
      'Implemented multi-head self-attention, residual connections, layer normalization, and sinusoidal positional encoding from scratch in PyTorch.',
      'Character-level modeling keeps the vocabulary flexible — the model adapts to any language or domain with no predefined tokenization rules.',
      'Trained with AdamW and periodic train/validation loss estimation, generating text autoregressively via multinomial sampling from any seed context.',
    ],
    accent: 'attention',
  },
  {
    slug: 'harmony-ai',
    num: '10',
    title: 'Harmony',
    titleIt: 'AI',
    year: '2024',
    role: 'Team build',
    category: 'AI · Agents',
    summary: 'Slack-native assistant unifying Trello, Gmail, and Calendar.',
    desc: 'AI productivity assistant that lives in Slack, built by a six-person NYU team. Plain commands like add "task" to [list] by date create Trello cards with matching Google Calendar events, checklists nest inside cards, and a background Gmail bot posts unread emails straight into channels — one interface, four tools, no context switching.',
    stack: ['Slack API', 'Trello API', 'Gmail API', 'Google Calendar API', 'Python'],
    links: { github: 'https://github.com/isiddharthsingh/mAIgic-nyu/tree/hw3_submission' },
    highlights: [
      'Built command-driven Trello management from Slack — add and remove tasks, nest checklists inside cards, list and archive boards — with due dates automatically mirrored to Google Calendar events.',
      'Ran a threaded Gmail bot that periodically fetches unread emails and posts them to Slack on request, down to a specific count ("show me 5 emails").',
      'Kept the team codebase healthy with pytest suites, ruff linting, mypy type checking, and a CircleCI pipeline running all three on every push.',
    ],
    accent: 'hub',
  },
  {
    slug: 'hashtable-benchmark',
    num: '11',
    title: 'Hashtable',
    titleIt: 'Benchmark',
    year: '2024',
    role: 'Solo build',
    category: 'Systems · Concurrency',
    summary: 'Measuring lock strategies on a multithreaded hash table.',
    desc: 'A study of synchronization under contention. A lock-free baseline demonstrates lost updates from race conditions; per-bucket mutexes, reader–writer locks, and spinlocks each fix it at different costs. A driver sweeps thread counts and records insert and retrieve timings for comparison.',
    stack: ['C', 'POSIX threads', 'Mutexes', 'RW locks', 'Spinlocks'],
    links: { github: 'https://github.com/isiddharthsingh/Multithread-Hashtable-Benchmark' },
    highlights: [
      'Demonstrated race-condition data loss with an unlocked baseline, then eliminated it with per-bucket mutexes.',
      'Compared mutex, reader–writer, and spinlock strategies across thread counts, measuring speed, CPU usage, and data integrity.',
    ],
    accent: 'buckets',
  },
  {
    slug: 'resume-maestro',
    num: '12',
    title: 'Resume',
    titleIt: 'Maestro',
    year: '2024',
    role: 'Solo build',
    category: 'AI · Tools',
    summary: 'GPT-4 resume optimizer with LaTeX-quality PDF output.',
    desc: 'Upload a resume PDF and a job description, download a resume rewritten for the posting. PyMuPDF extracts the text, GPT-4 optimizes the content against the description, and the backend typesets the result to LaTeX and compiles a polished PDF — both downloadable. Streamlit front end over a FastAPI backend, with one-click re-optimization if the first draft is not right.',
    stack: ['GPT-4', 'FastAPI', 'Streamlit', 'LaTeX', 'PyMuPDF', 'Docker'],
    links: { github: 'https://github.com/isiddharthsingh/Resume-Maestro' },
    highlights: [
      'Built the extraction-to-typesetting pipeline: PyMuPDF text extraction, GPT-4 content optimization against the job description, and LaTeX generation compiled to PDF.',
      'Served it as a Streamlit app over a FastAPI backend with direct download of both the .tex source and the finished PDF, and one-click re-optimization.',
    ],
    accent: 'resume',
  },
  {
    slug: 'tubegenie',
    num: '13',
    title: 'Tube',
    titleIt: 'Genie',
    year: '2024',
    role: 'Solo build',
    category: 'AI · RAG',
    summary: 'Ask questions of any YouTube video, answered by GPT-4-turbo.',
    desc: 'Ask questions of any YouTube video. Paste a URL — the app extracts the video ID, Embedchain ingests and embeds the content, ChromaDB stores the vectors for similarity search, and GPT-4-turbo answers grounded in what the video actually says. A cleanup control tears down the temporary storage when the session ends.',
    stack: ['GPT-4-turbo', 'Embedchain', 'ChromaDB', 'Streamlit', 'Python'],
    links: { github: 'https://github.com/isiddharthsingh/TubeGenie' },
    highlights: [
      'Built retrieval-augmented Q&A over video content: Embedchain ingestion and embedding, ChromaDB vector storage, and similarity-search retrieval feeding GPT-4-turbo.',
      'Interactive Streamlit interface with URL-based ingestion and a one-click cleanup that releases temporary databases and resources after each session.',
    ],
    accent: 'video',
  },
  {
    slug: 'llamalingo',
    num: '14',
    title: 'Llama',
    titleIt: 'Lingo',
    year: '2024',
    role: 'Solo build',
    category: 'AI · Conversational',
    summary: 'Llama-3 chatbot served entirely from a local machine.',
    desc: 'Chatbot on Llama-3 that never leaves your machine. LM Studio hosts the Llama-3 instruct model and exposes it as an OpenAI-compatible API on localhost:1234, and a Streamlit front end handles the conversation with real-time chat history — the same client code as the cloud API, with zero cloud dependency.',
    stack: ['Llama-3', 'LM Studio', 'Streamlit', 'OpenAI API', 'Python'],
    links: { github: 'https://github.com/isiddharthsingh/LlamaLingo' },
    highlights: [
      'Served the Llama-3 instruct model locally through LM Studio as an OpenAI-compatible endpoint, keeping every conversation private and offline.',
      'Built a Streamlit chat interface with real-time message display and dynamic chat-history management.',
    ],
    accent: 'localchat',
  },
  {
    slug: 'ecostock',
    num: '15',
    title: 'Eco',
    titleIt: 'Stock',
    year: '2024',
    role: 'Solo build',
    category: 'Data · Forecasting',
    summary: 'Stock forecasting driven by ESG metrics and sentiment.',
    desc: 'Can ESG signals improve stock forecasts? Six time-series models — ARIMA, SMA, exponential smoothing, SARIMAX, VARMAX, and OLS — forecast META stock from Alpha Vantage price history enriched with news-sentiment scores engineered per ESG category. VARMAX performed best on AIC (1338.44), and OLS reached an R-squared of 0.698, with model selection by AIC, BIC, and HQIC.',
    stack: ['Python', 'VARMAX', 'SARIMAX', 'ARIMA', 'Alpha Vantage'],
    links: { github: 'https://github.com/isiddharthsingh/EcoStock-ESG-Driven-Market-Predictions' },
    highlights: [
      'Engineered per-category ESG sentiment features from the Alpha Vantage News Sentiment API and joined them with historical prices for META Platforms.',
      'Compared six models (ARIMA, SMA, exponential smoothing, SARIMAX, VARMAX, OLS) using AIC, BIC, and HQIC — VARMAX won with an AIC of 1338.442.',
      'Quantified predictor strength with an OLS R-squared of 0.698 and visualized sentiment-price relationships through time-series plots, correlation heatmaps, and distribution plots.',
    ],
    accent: 'esg',
  },
  {
    slug: 'typeninja',
    num: '16',
    title: 'Type',
    titleIt: 'Ninja',
    year: '2024',
    role: 'Solo build',
    category: 'Web · Game',
    summary: 'A typing game that takes away your backspace.',
    desc: 'Typing game with live WPM, accuracy, and timing across 20 randomized sentences. Backspace is disabled by design — accuracy is the game. Clean, responsive, playable on anything.',
    stack: ['React', 'JavaScript', 'HTML', 'CSS'],
    links: { github: 'https://github.com/isiddharthsingh/TypeNinja' },
    highlights: [
      'Real-time tracking of typing time, accuracy, and words per minute.',
      'Disabled backspace to force focused, accurate typing across randomized sentences.',
    ],
    accent: 'keys',
  },
  {
    slug: 'shems',
    num: '17',
    title: 'Smart Home',
    titleIt: 'Energy',
    year: '2023',
    role: 'Solo build',
    category: 'Web · Full Stack',
    summary: 'Smart-home dashboard for devices and energy analytics.',
    desc: 'Web interface for managing smart devices and understanding their energy use. Users register service locations, add devices with types and models picked from a pre-stored catalog (a Bosch 800 refrigerator, an IKEA smart bulb, a GE 4500 air conditioner), and explore consumption through four to five graphical views. Node.js over a custom relational schema, hardened for concurrent multi-user access.',
    stack: ['Node.js', 'Bootstrap', 'SQL', 'JavaScript'],
    links: { github: 'https://github.com/isiddharthsingh/Smart-Home-Energy-Management-System-SHEMS' },
    highlights: [
      'Built registration, login, and the full device lifecycle — service locations, device types, and models selected from a pre-stored catalog.',
      'Delivered energy-consumption analysis through 4–5 graphical views over a custom relational schema.',
      'Hardened the multi-user environment with hashed passwords, pooled connections, and protections against SQL injection and XSS.',
    ],
    accent: 'energy',
  },
];

Object.assign(window, { PROJECTS });
